apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sluice.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sluice.labels" . | nindent 4 }}
data:
  SLUICE_POSTGRES_URL: {{ .Values.postgres.url | quote }}
  SLUICE_REDIS_ADDR: {{ .Values.redis.addr | quote }}
  SLUICE_ETCD_ENDPOINTS: {{ .Values.etcd.endpoints | quote }}
  SLUICE_PORT: {{ .Values.api.port | quote }}
