apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sluice.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sluice.labels" . | nindent 4 }}
data:
  SLUICE_ETCD_ENDPOINTS: {{ .Values.etcd.endpoints | quote }}
  {{- with .Values.etcd.username }}
  SLUICE_ETCD_USERNAME: {{ . | quote }}
  {{- end }}
  SLUICE_PORT: {{ .Values.api.port | quote }}
